### ISSUE TITLE
Lua 5.1 and 5.2 support (luaL_tolstring and bit module)

### ISSUE THREAD

**Issue by rolandlo** [Tekenlight/luaffifb#3] opened 2024-03-19 10:40 UTC
Hi @sudheerhebbale again!

Now when testing `luaffi-tkl` with Lua 5.1 and Lua 5.2 two following two issues have appeared:

- Lua 5.1 doesn't know `luaL_tolstring` (used in `stringified_cdata_concat`). Maybe it could simply be replaced by `lua_tolstring`.
- The bit-module (`bit.lua`) uses bitwise operators that have only been introduced in Lua 5.3. For Lua 5.1 and 5.2 using https://luarocks.org/modules/luarocks/luabitop seems to work instead. When I install `luabitop` locally using `luarocks` it removes `bit.lua` from `luaffi-tkl` and places it `bit.so` into the `lib/lua/5.2` folder and things work. In the CI https://github.com/libvips/lua-vips/pull/67/checks it didn't work out that way (`bit.lua` was not removed when installing `luabitop`).

**Comment by sudheerhebbale** [comment] 2024-03-19 15:56
Hi @rolandlo ,

Will take this up.

The first issue is relatively simple

bit operation module is used in dynasm module, this was not present at the time fork was created from luaffifb.
Later while working on ARM64, it became necessary to reconcile the newer commits into dynasm, the reconciliation brought in the dependency of bit module as well. The luabitop did not work with lua 5.3 for some reason (forgetting what the issue is). Thus ended up developing bit.lua, which has broken the module for 5.1 and 5.2

Need some time (a couple of days) to fix the second one reasonably.

**Comment by sudheerhebbale** [comment] 2024-03-20 06:09
> * The bit-module (`bit.lua`) uses bitwise operators that have only been introduced in Lua 5.3. For Lua 5.1 and 5.2 using https://luarocks.org/modules/luarocks/luabitop seems to work instead. When I install `luabitop` locally using `luarocks` it removes `bit.lua` from `luaffi-tkl` and places it `bit.so` into the `lib/lua/5.2` folder and things work. In the CI https://github.com/libvips/lua-vips/pull/67/checks it didn't work out that way (`bit.lua` was not removed when installing `luabitop`).

Within luaffi-tkl bit.lua is used only within the dynasm (dynamic-assembler generator), so if I remove bit.lua from the rockspec and install luaffi-tkl, it is working fine on lua5.1 (i.e. all the test cases are passing), will check for 5.2 as well.

The long and short of this is, bit.lua is needed only for assembly code generation and not in the runtime of ffi and the generated assembly code is part of the checked in source code.
Hence, removing bit.lua from the rockspec should just work fine.

BTW, is your code using bitop library for any other reason?

**Comment by rolandlo** [comment] 2024-03-20 07:07
> BTW, is your code using bitop library for any other reason?

The only thing the `lua-vips` code uses bit operations is `bit.band` on two arguments. I can deal with the removal of `bit.lua` from `luaffi-tkl`.

**Comment by sudheerhebbale** [comment] 2024-03-20 07:48
Pushed the changes

Please confirm if it is working

**Closed as completed** 2024-03-29 07:38 UTC

**Comment by rolandlo** [comment] 2024-03-29 07:40
I forgot to confirm. It works fine.
